### ISSUE TITLE
where to get spotify accounts?

### ISSUE THREAD

**Issue by ghost** [VoldemortCommunity/SpotifyChecker#2]
and how do i use this??

**Comment by voldemort1912** [comment]
SpotifyChecker is a Penetration Testing Tool which allows you to Input raw combos(email@example.com:password) and Filter out hits with Requisite Details.
If you want a Spotify Account, Go Buy it. I am Not Responsible for any Malpractice. But i can tell you how to use the Program ;). Join me on [THIS](https://t.me/VoldemortCommunity) telegram Group and Ask how to use it. Anyone will let you know ;)
