### ISSUE TITLE
CSRF Cookie Regex not specific enough

### ISSUE THREAD

**Issue by mgoerlich-dev** [VoldemortCommunity/SpotifyChecker#3]
**Summary**
It's not working anymore. Every Account i test is recognized as invalid with the reason "errorCSRF".
That implies Spotify changed their CSRF check to prevent mass checking.

**Steps to reproduce**
1. Put a 100% working account into your Combo List
2. run checker.php
3. Output will be: 
```
[!] Email ID : user@host.tld
[!] Password : insecurepw
[!] Invalid Account! 
[!] errorCSRF
```

**EDIT**
Nevermind, the csrf check didn't change that much, but when the Regex to detect the set-cookie header ist to unspecific so it'll match the very first set-cookie header it finds, no matter if it's the csrf token or not.

Try ```/^Set-Cookie:\s*(csrf[^;]*)/mi```, that worked for me

**Comment by voldemort1912** [comment]
Thank You VERY much. I was just about to fix the regex
