### ISSUE TITLE
Subscription, Country, and Validity not showing.

### ISSUE THREAD

**Issue by gvoze32** [VoldemortCommunity/SpotifyChecker#5]
**Describe the bug**
Subscription, Country, and Validity not showing.

**Screenshots**
![image](https://user-images.githubusercontent.com/28755051/68258824-85d3b900-006a-11ea-819d-05eb2beecaea.png)

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser Mozilla Firefox
 - Version Latest

**Comment by voldemort1912** [comment]
The error has been resolved in the coming Update, the update will be released soon, thank you for pointing it out
